options(repos='https://cloud.r-project.org')
if (!requireNamespace('haven', quietly = TRUE)) install.packages('haven')
source('data-raw/fetchers/fetch_nhanes.R')
source('data-raw/fetchers/fetch_brfss.R')
source('data-raw/fetchers/fetch_nhis.R')
fetch_nhanes_demo()
fetch_brfss(2019:2022)
fetch_nhis_sample_adult(2019:2022)
message('Fetched public IPD datasets to inst/extdata')
