name: Fetch Public IPD

on:
  schedule:
    - cron: '0 1 * * *'   # daily at 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install R packages
        run: |
          Rscript -e "options(repos='https://cloud.r-project.org'); if (!requireNamespace('haven', quietly=TRUE)) install.packages('haven'); if (!requireNamespace('readr', quietly=TRUE)) install.packages('readr')"
      - name: Run fetch orchestrator
        run: |
          Rscript data-raw/fetchers/fetch_all_public.R
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add inst/extdata inst/registry/registry.csv data-raw/summary || true
          git commit -m "CI: fetch public IPD datasets" || echo "No changes to commit"
          git push
